### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [firas-assaad/octopus_engine#1]
Hey! I really like this project and I'd like to contribute to it by designing a logo. If you'd want that, please let me know if there are any specific things you'd want this logo to represent, and if you don't have any I'll just implement my own ideas.

**Comment by firas-assaad** [comment]
Hi. I really appreciate the offer. Right now this personal project is only used by me and getting more people on board isn't a priority. Making a logo for it would be making a logo for only one person. I'm sure there are more popular projects out there that need a logo.

Thanks for reaching out!

**Comment by newfinal100** [comment]
That's okay :) Thanks for letting me know!
